stages:
    - test
    - deploy

.setup_eb: &setup_eb
    - module use $HOME/.local/easybuild/modules/all
    - ml EasyBuild
    - source setup.sh
    - eb --show-config

eb_dryrun:
  tags: ["eb-perlmutter"]
  stage: deploy
  script:
    - *setup_eb
    - eb easyconfigs/* -D --robot --prefix=$CI_PROJECT_DIR/easybuild_stage

eb_install:
  tags: ["eb-perlmutter"]
  stage: deploy
  needs: [eb_dryrun]
  script:
    - *setup_eb
    - eb easyconfigs/* --robot --prefix=$CI_PROJECT_DIR/easybuild_stage
