#!/bin/bash
if [ -z "$NERSC_EASYBUILD_DIR" ]; then
	NERSC_EASYBUILD_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
fi

export EASYBUILD_CONFIGFILES=$NERSC_EASYBUILD_DIR/perlmutter.config
export EASYBUILD_REPOSITORYPATH="$NERSC_EASYBUILD_DIR,easyconfigs"
export EASYBUILD_ROBOT_PATHS=$NERSC_EASYBUILD_DIR/easyconfigs:$EASYBUILD_ROBOT_PATHS
export EASYBUILD_SEARCH_PATHS=$NERSC_EASYBUILD_DIR/easyconfigs

